// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Api.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace Api.Models.Configurations
{
    public partial class RecipientConfiguration : IEntityTypeConfiguration<Recipient>
    {
        public void Configure(EntityTypeBuilder<Recipient> entity)
        {
            entity.ToTable("Recipient");

            entity.Property(e => e.UserName).HasMaxLength(50);
        }
    }
}
