// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
namespace Api.Models;

public partial class Recipient
{
    public int Id { get; set; }

    public string UserName { get; set; }
}